import PDFDocument from "pdfkit";
import { prisma } from "../lib/prisma";

export async function buildInvoicePdf(
  userId: string,
  businessId: string,
  invoiceId: string,
) {
  const invoice = await prisma.invoice.findFirst({
    where: {
      id: invoiceId,
      businessId,
      business: { userId },
    },
    include: {
      business: true,
      customer: true,
      items: true,
    },
  });

  if (!invoice) throw new Error("INVOICE_NOT_FOUND");

  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const chunks: Buffer[] = [];

  return new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(22).text(invoice.business.displayName || invoice.business.legalName);
    doc.fontSize(10).text(invoice.business.address || "");
    doc.text(invoice.business.state || "");
    if (invoice.business.gstin) doc.text(`GSTIN: ${invoice.business.gstin}`);

    doc.moveDown(1);
    doc.fontSize(18).text(`INVOICE ${invoice.invoiceNumber}`);
    doc.fontSize(10).text(`Status: ${invoice.status}`);
    doc.text(`Invoice Date: ${invoice.invoiceDate.toISOString().slice(0, 10)}`);
    if (invoice.dueDate) {
      doc.text(`Due Date: ${invoice.dueDate.toISOString().slice(0, 10)}`);
    }

    doc.moveDown(1);
    doc.fontSize(12).text("Bill To");
    doc.fontSize(10).text(invoice.customer?.name || "Customer");
    if (invoice.customer?.companyName) doc.text(invoice.customer.companyName);
    if (invoice.customer?.address) doc.text(invoice.customer.address);
    if (invoice.customer?.gstin) doc.text(`GSTIN: ${invoice.customer.gstin}`);

    doc.moveDown(1);
    doc.fontSize(11).text("Items");
    doc.moveDown(0.5);

    invoice.items.forEach((item, index) => {
      doc.fontSize(10).text(
        `${index + 1}. ${item.description} | Qty: ${item.quantity.toString()} | Rate: ₹${item.rate.toString()} | Tax: ${item.taxRate.toString()}% | Amount: ₹${item.amount.toString()}`
      );
    });

    doc.moveDown(1);
    doc.fontSize(11).text(`Subtotal: ₹${invoice.subtotal.toString()}`);
    doc.text(`Discount: ₹${invoice.discount.toString()}`);
    doc.text(`Taxable Amount: ₹${invoice.taxableAmount.toString()}`);
    doc.text(`CGST: ₹${invoice.cgst.toString()}`);
    doc.text(`SGST: ₹${invoice.sgst.toString()}`);
    doc.fontSize(14).text(`Total: ₹${invoice.total.toString()}`);

    if (invoice.notes) {
      doc.moveDown(1);
      doc.fontSize(10).text(`Notes: ${invoice.notes}`);
    }

    doc.moveDown(2);
    doc.fontSize(9).text("Generated by HisabBookes");

    doc.end();
  });
}
